all:
	g++ Lab1.cpp GLSL_helper.cpp CMeshLoaderSimple.cpp GameObject.cpp mesh.cpp CMesh.cpp -DGL_GLEXT_PROTOTYPES -lglfw3  -Wno-deprecated -framework IOKit -framework OpenGL -framework Cocoa -framework CoreVideo

